### ISSUE TITLE
Stl file and other questions: Orig: Cannot load the stl file in the 3D printer software "FlashPrint5"

### ISSUE THREAD

**Issue by ozilxu** [jasonmhead/open-tentacle#22]
Hi @jasonmhead , may I ask how to load the **STL** files in this repository into the 3D printer slicer software (https://www.flashforge.com/product-detail/FlashPrint-slicer-for-flashforge-fdm-3d-printers)? Now, after I uploaded the file, the software cannot show anything. Or can you recommend other 3D printer slicer software to process these STL files? Thank you very much!!!
![image](https://user-images.githubusercontent.com/38513040/175456133-4d394d6b-c458-4f1a-9f2b-5070e1ca285e.png)

**Comment by jasonmhead** [comment]
Hello,
Which file are you using?

I use Cura personally for the 3D slicing.

**Comment by ozilxu** [comment]
hello, Jason @jasonmhead ! I have tried all the stl files in the accessories directory but no one works. I will try Cura for the slicing. Thanks!

**Comment by ozilxu** [comment]
@jasonmhead  Hi Jason, are the continuum robots consisting of all the **STL** files in the **accessories** directory??

**Comment by jasonmhead** [comment]
@ozilxu accessories are helper items, but the full concepts are in the versioned directory folders 0.0.1 - 0.1.2
Things are very much in alpha stage, and I need to update things to the most recent prototype being worked on.

The most upto date things are on instagram at the moment:
https://www.instagram.com/head_robotics/

I created a wiki page that has a project update on it:
https://github.com/jasonmhead/open-tentacle/wiki

In building your own version the essential mechanical hardware is:
- the arm vertebrae disk to go on the flexible plastic tube, and to host the tendons:
https://github.com/jasonmhead/open-tentacle/blob/main/0.1.1/spine_vert.stl

- some sort of frame to mount on with the motors below

- motors with pulleys

I'm going to close this issue, and we can try to do one per topic, but feel free to open additional ones.

**Comment by ozilxu** [comment]
> @ozilxu accessories are helper items, but the full concepts are in the versioned directory folders 0.0.1 - 0.1.2 Things are very much in alpha stage, and I need to update things to the most recent prototype being worked on.
> 
> The most upto date things are on instagram at the moment: https://www.instagram.com/head_robotics/
> 
> I created a wiki page that has a project update on it: https://github.com/jasonmhead/open-tentacle/wiki
> 
> In building your own version the essential mechanical hardware is:
> 
> * the arm vertebrae disk to go on the flexible plastic tube, and to host the tendons:
>   https://github.com/jasonmhead/open-tentacle/blob/main/0.1.1/spine_vert.stl
> * some sort of frame to mount on with the motors below
> * motors with pulleys
> 
> I'm going to close this issue, and we can try to do one per topic, but feel free to open additional ones.

@jasonmhead  Hi Jason, thanks very much for the updates! May I ask what kinds of these components are? What are the functions? 
![image](https://user-images.githubusercontent.com/38513040/176817828-714c6d7a-d1eb-4c3c-864f-9268d7119a5d.png)

**Comment by jasonmhead** [comment]
Those are cable pressure sensors; this is the old version that had a thin film pressure sensor.
I wasn't able to get that to work I think.

That setup might work with enough tweaks but sensitivity range configuration could have been a significant challenge.

I will still use the outer shell that transfers pressure, but for the next version I think I will be using tubes filled with oil to transfer the pressure to a sensor.

Here is a post I did on the module: https://headrobotics.co/cable-tension-sensor-module/

**Comment by ozilxu** [comment]
@jasonmhead Thanks for clarifying！ May I ask if this pressure means the cable tension force? So is the sensor for measuring the tension of one cable?

**Comment by jasonmhead** [comment]
Pressure that is created by cable tension; one sensor package per cable.

The way I envision it working is that instead of a thin film pressure sensor, there would be a oil filed pouch that would be squeezed and that pressure would be transferred down a tube where it will be measured by a pressure sensor.

**Comment by ozilxu** [comment]
Thanks! Did you want to measure the pressure from the cable to the rigid disk? In this case, will you use the cosserat rod model to model the continuum robot?

Besides, may I have your email to contact? Also, I have seen in your video that you are making a modular tendon-driven mechanism, is it shown on your website now?

Thanks a lot for your time and effort!

**Comment by jasonmhead** [comment]
The cable tension is what would be measured - how tight it is being pulled - the pressure that is created when the cable is pulled.

I'm not sure if the cosserat rod model would be useful for my application.
For modeling, I have done a motion study, and am working on a second.
See :56 sec here
https://www.youtube.com/watch?v=jhXhIMkDN2g

Hopefully a software simulation can be used - I may develop / have develop one down the road if I don't run into a good opensource one.

The above YouTube link shows the prototype, but I have done some updates to the system, and haven't put that video up yet.

you can reach me via email at (replacing spaces etc) jmhead @ jasonmhead DOT com

**Comment by henrychulab** [comment]
@jasonmhead Thanks for the answering! |

I remember in your previous video: https://www.youtube.com/watch?v=bMghezxvwAc, you want to design a modular cable-driven mechanism (motors with the cable). May I ask if you have done this part of the modular design?

Thanks again!

**Comment by jasonmhead** [comment]
I have motors and cables in the current prototype.
Here is what it currently looks like.
Things can be more developed in future versions as things are worked out.

![image](https://user-images.githubusercontent.com/6140151/186164200-5a2a6c7a-984e-409b-a5b0-81a7c4f09c1a.jpeg)
